server:
  port: 8060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dropbaba_auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:classpath:application-secrets.yml
  cloud:
    config:
      enabled: false

logging:
  level:
    org.springframework.security: DEBUG
