spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 464597998565-cbbkci56sj5cmitqdll69tqg6q1rsr10.apps.googleusercontent.com
            client-secret: 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
